export const excom_sb_2021 = [
    {
        name: 'Srilal Sachintha',
        position: 'Chairperson',
        image_path: '/Assets/Chair/Srilal.png',
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: 'Sanjula De Alwis',
        position: 'Co Chairperson - FOC',
        image_path: '/Assets/Chair/Sanjula.png',
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Mahasen Abheetha",
        image_path: '/Assets/Excom/Janith bandara.png',
        position: "Co Chairperson - FOE",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Lihini Nisansala",
        image_path: '/Assets/Excom/Lihini Nisansala.jpg',
        position: "Secretary",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Nirasha Herath",
        image_path: '/Assets/Excom/NirashaH.jpg',
        position: "Asst. Secretary",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Vinuri Prabodhya",
        image_path: '/Assets/Excom/Vinuri Prabodhya.jpg',
        position: "Treasurer",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Senith Edirisinghe",
        image_path: '/Assets/Excom/SenithE.jpg',
        position: "Asst. Treasurer",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Prineth Fernando ",
        image_path: '/Assets/Excom/PrinethF.jpg',
        position: "Web Master",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Isura Dilshan",
        image_path: '/Assets/Excom/IsuraD.jpg',
        position: "Designer",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Sandaru Dilshan Silva",
        image_path: '/Assets/Excom/SandaruD.jpg',
        position: "Volunteer Coodinator",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Ranu Pathiranage",
        image_path: '/Assets/Excom/RanuP.jpg',
        position: "Media Coodinator",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Rashenka Savindi",
        image_path: '/Assets/Excom/RashenkaS.jpg',
        position: "Event Coodinator",
        linkedin: '#',
        facebook: '#',
        email: '#',
    }
]

export default { excom_sb_2021 };
