export const excom_sb_2022 = [
    {
        name: 'Isura Dilshan',
        position: 'Chairman',
        image_path: '/Assets/Chair/Isura.jpg',
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: 'Dasanjith Gunaratne',
        position: 'Vice Chairman - FOC',
        image_path: '/Assets/Chair/Dasanjith Gunarathne.jpg',
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Gayara Alahakoon",
        image_path: '/Assets/Excom/Gayara.jpg',
        position: "Vice Chairman - FOE",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "NIRASHA HERATH",
        image_path: '/Assets/Chair/Nirasha.jpg',
        position: "Secretary",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "DEWMI HATHURUSINGHA",
        image_path: '/Assets/Excom/Dewmi Hathurusingha.jpg',
        position: "Asst. Secretary",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "SENITH EDIRISINGHE",
        image_path: '/Assets/Excom/Senith.jpg',
        position: "Treasurer",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "CHATHRANGA SENARATHNE",
        image_path: '/Assets/Excom/Chathuranga Senarathne.jpg',
        position: "Asst. Treasurer",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "NALINDA GAMAARACHCHI",
        image_path: '/Assets/Excom/Nalinda Gamaarachchi.jpg',
        position: "Web Master",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "SUBODHA HERRIARACHCHI",
        image_path: '/Assets/Excom/Subodha Hettiarachhi.jpg',
        position: "Designer",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "ISHADI HANDAPANGODA",
        image_path: '/Assets/Excom/Ishadi.jpg',
        position: "EVENT COORDINATOR",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "SHAVINDA WANNIARACHCHI",
        image_path: '/Assets/Excom/Shavinda Wanniarachchi.jpg',
        position: "MEDIA COORDINATOR",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "CHATHURA MALLAWARACHCHI",
        image_path: '/Assets/Excom/Chathura Mallawarchchi.jpg',
        position: "VOLUNTEER COORDINATOR",
        linkedin: '#',
        facebook: '#',
        email: '#',
    }
]

export default { excom_sb_2022 };
