export const excom_sb_2022 = [
    {
        name: 'Denver Shenal',
        position: 'Chairman',
        image_path: '/Assets/Excom/President.jpg',
        linkedin: 'https://www.linkedin.com/in/denver-shenal-9b1b3b1b1/',
        facebook: 'https://www.facebook.com/denver.shenal.1',
        email: '#',
    },
    {
        name: 'Pubudu Rathnayake',
        position: 'Vice Chairman',
        image_path: '/Assets/Excom/VicePresident_A.jpg',
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Mahasen Abheetha",
        image_path: '/Assets/Excom/VicePresident_B.jpg',
        position: "Vice Chairman",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Sunali Rambukwella",
        image_path: '/Assets/Excom/Secretary.jpg',
        position: "Secretary",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Gangadara Athukorala",
        image_path: '/Assets/Excom/AsstSecretary.jpg',
        position: "Asst. Secretary",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Anne Kaushalya ",
        image_path: '/Assets/Excom/Anne Kaushalya.jpg',
        position: "Asst. Secretary",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Pasan Jayawickrama",
        image_path: '/Assets/Excom/Treasurer.jpg',
        position: "Treasurer",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Sanjula De Alwis",
        image_path: '/Assets/Excom/Sanjula.png',
        position: "Asst. Treasurer",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Srilal Sachintha ",
        image_path: '/Assets/Excom/WebMaster.jpg',
        position: "Web Master",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Pasindu Sandeepa",
        image_path: '/Assets/Excom/Pasindu Sandeepa.png',
        position: "Editor",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Kaveen De Alwis",
        image_path: '/Assets/Excom/Kaveen Hyacinth.jpg',
        position: "Main Coordinator",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Pasan Chinthaka",
        image_path: '/Assets/Excom/Pasan Chinthaka.png',
        position: "Main Coordinator",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Janith Bandara",
        image_path: '/Assets/Excom/Janith bandara.png',
        position: "PR Manager",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Lihini Nisansala",
        image_path: '/Assets/Excom/Lihini Nisansala.jpg',
        position: "Activity Director",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Kaveesha pathirana",
        image_path: '/Assets/Excom/Kaveesha Pathirana.jpg',
        position: "Director of Logistics",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Manuja Mallikarachchi",
        image_path: '/Assets/Excom/Manuja Mallikarachchi.png',
        position: "Director Of Media & promotion",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Geetham Ramanayaka",
        image_path: '/Assets/Excom/Geethmi.png',
        position: "Volunteer Coodinator",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Isuri Mayadunne",
        image_path: '/Assets/Excom/Isuri Mayadunne.jpg',
        position: "Volunteer Coodinator",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Sewmini Amasha",
        image_path: '/Assets/Excom/Sewmini.png',
        position: "Director of Member Development",
        linkedin: '#',
        facebook: '#',
        email: '#',
    },
    {
        name: "Mishani Poornika",
        image_path: '/Assets/Excom/Mishani Poornika.png',
        position: "Director of Member Development",
        linkedin: '#',
        facebook: '#',
        email: '#',
    }
]

export default { excom_sb_2022 };
