#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\n👀 Checking format, lint, and types in your project before committing...🔎"

# Check code formatting with Prettier
npm run check-format ||
(
    echo "\n❌ Prettier Check Failed.❌\n Run  npm run format, add changes and try commit again.👀 \n"
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo "\n❌ ESLint Check Failed.❌\n Make the required changes listed above, add changes and try to commit again.👀 \n"
    false;
)

# If everything passes, we can now commit
echo "✅ Commit Hook Passed! Committing changes now. 💪\n"
